version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: jovanio-tldraw_web_1
      APP_PORT: 80

  web:
    image: jumbrelappson/tldraw:5.1.0-sync.1@sha256:1bd87b0d256d8769d1f0c17896bd29a121264ae3cbda7e0d90024cc798482e75
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
